### PR TITLE
Test the context methods, rather than just `the`.

### PR DESCRIPTION
**Pull request by gma**
Skipped the test for `and` out as it's a syntax error.

### CODE REVIEW

**Comment by itstommymorgan** [comment]
Good catches both. Obviously we hadn't run into an actual use-case for "and" but were getting ahead of ourselves in terms of setting up grammar.

What do we think about just whacking 'and' altogether? Or would it be worthwhile to replace it with something like "and_also" that can serve the same function but doesn't, you know, try to override a Ruby keyword? :smile:

**Comment by nalanj** [comment]
I say just axe it and add something like that if it comes up as being handy.

**Comment by gma** [comment]
I thought about sending you a patch with an alternative to "and", but thought it better to discuss the options first. I was thinking just "also" might be a good substitute, but it really comes down to the kinds of sentences that are formed. If we used "also" I'd be tempted to make the first word of the name parameter "having" all the time. Like this:

```
also "having …" do
```

It's a waste of a word. `and_also` would deal with that, and isn't likely to clash with anything else.

I can add another commit to the pull request if you like; let me know.

I'd be quite happy to keep typing `context` (and to set that alias up in my own project) if `minitest-rails` hadn't already added it as an alias to minispec's `describe`.

**Comment by itstommymorgan** [comment]
@gma sure, if you want to go ahead and add "and_also" and drop a test in for it we can just merge this in. It's not exactly a big change to the code so while I'd normally agree with @commondream's sentiment, I don't see any reason not to just go ahead and add it.

One of the things we didn't want to do here was go with something standard like "context" or "describe" because those are a bit less readable, and you pretty much always end up typing "that," "a," "an," etc. just like you'd always type "also" above. I think turning those articles into the function names actually makes it a bit easier to read and work with.

**Comment by itstommymorgan** [comment]
Thanks for the commits @gma. They've been merged in and nutrasuite 0.3.0 is released.

**Comment by gma** [comment]
I just upgraded; working nicely thanks. Cheers for the credit too.

**Pull request merged**
